apiVersion: v1
kind: Service
metadata:
    name: broken-timber-svc
spec:
    type: ClusterIP
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 7080
    selector:
        tier: frontend
